spring:
  profiles:
    active: local
  application:
    name: SongLei


employee:
  output: src/main/resources/b.txt
  
server:
  port: 5090

logging:
  file:
    name: src/main/resources/application.log
  pattern:
    console: "%d %p %thread %X{traceId} (%file:%line\\)- %m%n"
    file: "%d %p %thread %X{traceId} (%file:%line\\)- %m%n"
  charset:
    console: UTF-8
    file: UTF-8


