spring:
  profiles:
    active: local
  application:
    name: SongLei
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        '[enable_lazy_load_no_trans]': true
        jdbc:
          '[time_zone]': UTC
  datasource:
    url: jdbc:mysql://127.0.0.1:3406/SongLei?autoReconnect=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  servlet:
     multipart:
       max-file-size: -1 #infinite size
       max-request-size: -1

file:
  location: "classpath:/uploadDir"

server:
  port: 5090


